core/urls.py
import notifications
from django.contrib import admin
from django.shortcuts import render, redirect
from django.views.static import serve
from django.urls import path, include, re_path

from .settings import MEDIA_ROOT, STATIC_ROOT, ENVIRONMENT

""" __ ERROR HANDLERS AND VIEWS __ """


def handler404(request, *args, **kwargs):
    return render(request, "404.html")


def handler500(request, *args, **kwargs):
    return render(request, "500.html")


def home(request, *args, **kwargs):
    return redirect('accounts:login')


handler404 = handler404
handler500 = handler500

""" __ URLS __ """

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', home, name='home'),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('a/', include('src.administration.admins.urls', namespace='admins')),
    path('c/', include('src.administration.employees.urls', namespace='employees')),
    path('scheduler/', include('src.services.schedular.urls', namespace='scheduler')),
]

urlpatterns += [
    path('accounts/', include('allauth.urls')),
    path('inbox/notifications/', include('notifications.urls', namespace='notifications')),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
]

""" __ DEBUG URLS __ """

if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

src/accounts/urls.py
from django.urls import path
from .views import LoginView, LogoutView, UserUpdateView, UserPasswordChange, CrossAuth

app_name = 'accounts'
urlpatterns = [
    path('cross-auth/', CrossAuth.as_view(), name='cross-auth'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('user/change/', UserUpdateView.as_view(), name='user-change'),
    path('password/change/', UserPasswordChange.as_view(), name='user-password-change'),
]

src/administration/admins/urls.py
from django.urls import path, include
from .views import (
    DashboardView, TimeClockView, CheckCallsView,
    PositionListView, PositionDeleteView, PositionCreateView, PositionUpdateView,
    UserPasswordResetView, UserListView, UserStaffCreateView, UserEmployeeCreateView, UserUpdateView, UserDeleteView,
    ClientListView, ClientDetailView, ClientUpdateView, ClientDeleteView, ClientCreateView,
    SiteListView, SiteDetailView, SiteUpdateView, SiteDeleteView, SiteCreateView,
    ReportTypeListView, ReportTypeUpdateView, ReportTypeDeleteView, ReportTypeCreateView,
    ShiftDayUpdateView, ShiftDayDeleteView,
    ShiftCreateView, ShiftUpdateView, ShiftDeleteView, UserDetailView,
    ShiftListView, ShiftDetailView, ShiftCustomCreateView,
    CountryListView, CountryCreateView, CountryUpdateView, CountryDeleteView, SubContractorListView,
    SubContractorCreateView, SubContractorUpdateView, SubContractorDeleteView, SubContractorDetailView,
    DepartmentListView, DepartmentCreateView, DepartmentUpdateView, DepartmentDeleteView,

    AbsenseTypeListView, AbsenseTypeCreateView, AbsenseTypeDeleteView, AbsenseTypeUpdateView, AbsenseScheduleView,
    UserEmployeeInviteCreateView
)

app_name = 'admins'
urlpatterns = [
    path('', DashboardView.as_view(), name="dashboard"),
    path('time-clock/', TimeClockView.as_view(), name="time-clock"),
    path('absenses/', AbsenseScheduleView.as_view(), name="absense-schedule"),
    path('check-calls/', CheckCallsView.as_view(), name="check-calls"),
]

urlpatterns += [
    path('position/', PositionListView.as_view(), name='position-list'),
    path('position/add/', PositionCreateView.as_view(), name='position-add'),
    path('position/<int:pk>/change/', PositionUpdateView.as_view(), name='position-update'),
    path('position/<int:pk>/delete/', PositionDeleteView.as_view(), name='position-delete'),
]

urlpatterns += [
    path('country/', CountryListView.as_view(), name='country-list'),
    path('country/add/', CountryCreateView.as_view(), name='country-add'),
    path('country/<int:pk>/change/', CountryUpdateView.as_view(), name='country-update'),
    path('country/<int:pk>/delete/', CountryDeleteView.as_view(), name='country-delete'),
]

urlpatterns += [
    path('department/', DepartmentListView.as_view(), name='department-list'),
    path('department/add/', DepartmentCreateView.as_view(), name='department-add'),
    path('department/<int:pk>/change/', DepartmentUpdateView.as_view(), name='department-update'),
    path('department/<int:pk>/delete/', DepartmentDeleteView.as_view(), name='department-delete'),
]

urlpatterns += [
    path('shift/', ShiftListView.as_view(), name='shift-list'),
    path('shift/add/', ShiftCreateView.as_view(), name='shift-add'),
    path('shift/<int:pk>/', ShiftDetailView.as_view(), name='shift-detail'),
    path('shift/<int:pk>/change/', ShiftUpdateView.as_view(), name='shift-update'),
    path('shift/<int:pk>/delete/', ShiftDeleteView.as_view(), name='shift-delete'),
]

urlpatterns += [
    path('shift-day/<int:pk>/change/', ShiftDayUpdateView.as_view(), name='shift-day-update'),
    path('shift-day/<int:pk>/delete/', ShiftDayDeleteView.as_view(), name='shift-day-delete'),
]

urlpatterns += [
    path('client/', ClientListView.as_view(), name='client-list'),
    path('client/add/', ClientCreateView.as_view(), name='client-add'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client-detail'),
    path('client/<int:pk>/change/', ClientUpdateView.as_view(), name='client-update'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client-delete'),
]

urlpatterns += [
    path('site/', SiteListView.as_view(), name='site-list'),
    path('site/add/', SiteCreateView.as_view(), name='site-add'),
    path('site/<int:pk>/', SiteDetailView.as_view(), name='site-detail'),
    path('site/<int:pk>/change/', SiteUpdateView.as_view(), name='site-update'),
    path('site/<int:pk>/delete/', SiteDeleteView.as_view(), name='site-delete'),
]

urlpatterns += [
    path('report-type/', ReportTypeListView.as_view(), name='report-type-list'),
    path('report-type/add/', ReportTypeCreateView.as_view(), name='report-type-add'),
    path('report-type/<int:pk>/change/', ReportTypeUpdateView.as_view(), name='report-type-update'),
    path('report-type/<int:pk>/delete/', ReportTypeDeleteView.as_view(), name='report-type-delete'),
]

urlpatterns += [
    path('absense-type/', AbsenseTypeListView.as_view(), name='absense-type-list'),
    path('absense-type/add/', AbsenseTypeCreateView.as_view(), name='absense-type-add'),
    path('absense-type/<int:pk>/change/', AbsenseTypeUpdateView.as_view(), name='absense-type-update'),
    path('absense-type/<int:pk>/delete/', AbsenseTypeDeleteView.as_view(), name='absense-type-delete'),
]

urlpatterns += [
    path('sub-contractor/', SubContractorListView.as_view(), name='sub-contractor-list'),
    path('sub-contractor/add/', SubContractorCreateView.as_view(), name='sub-contractor-add'),
    path('sub-contractor/<int:pk>/', SubContractorDetailView.as_view(), name='sub-contractor-detail'),
    path('sub-contractor/<int:pk>/change/', SubContractorUpdateView.as_view(), name='sub-contractor-update'),
    path('sub-contractor/<int:pk>/delete/', SubContractorDeleteView.as_view(), name='sub-contractor-delete'),
]

urlpatterns += [
    path('user/', UserListView.as_view(), name='user-list'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/<int:pk>/change/', UserUpdateView.as_view(), name='user-update'),
    path('user/<int:pk>/delete/', UserDeleteView.as_view(), name='user-delete'),
    path('user/staff/add/', UserStaffCreateView.as_view(), name='user-staff-add'),
    path('user/employee/add/', UserEmployeeCreateView.as_view(), name='user-employee-add'),
    path('user/employee/invite/add/', UserEmployeeInviteCreateView.as_view(), name='user-employee-invite-add'),
    path('user/<int:pk>/reset/password/', UserPasswordResetView.as_view(), name='user-password-reset'),
]

urlpatterns += [
    path('api/', include('src.administration.admins.admins-api.urls', namespace='admins-api')),
    path('json/', include('src.administration.admins.admins-json.urls', namespace='admins-json'))
]

src/services/schedular/urls.py
from django.urls import path

from .views import (
    ScheduleView, ShiftAddModelView
)

app_name = "schedular"
urlpatterns = [
    path('', ScheduleView.as_view(), name='schedule'),
    path('model/shift/add/', ShiftAddModelView.as_view(), name='model_shift_add'),
]

templates/core/include/admin_header.html
{% load static %}

<li class="nav-item ">
    <a class="nav-link" href="{% url 'accounts:cross-auth' %}">
                                    <span class="nav-link-icon d-md-none d-lg-inline-block">
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             class="icon icon-tabler icon-tabler-home-bolt" width="24" height="24"
                                             viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                             stroke-linecap="round" stroke-linejoin="round">
                                             <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                             <path d="M19 10l-7 -7l-9 9h2v7a2 2 0 0 0 2 2h7.5"></path>
                                             <path d="M9 21v-6a2 2 0 0 1 2 -2h2c.661 0 1.248 .32 1.612 .815"></path>
                                             <path d="M19 14l-2 4h4l-2 4"></path>
                                        </svg>
                                    </span>
        <span class="nav-link-title">
                                        Dashboard
                                    </span>
    </a>
</li>

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle"
       data-bs-toggle="dropdown"
       data-bs-auto-close="outside" role="button" aria-expanded="false">
        <span class="nav-link-icon d-md-none d-lg-inline-block">
            <svg xmlns="http://www.w3.org/2000/svg"
                 class="icon icon-tabler icon-tabler-calendar-event" width="24" height="24"
                 viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                 stroke-linecap="round" stroke-linejoin="round">
                                           <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                           <rect x="4" y="5" width="16" height="16" rx="2"></rect>
                                           <line x1="16" y1="3" x2="16" y2="7"></line>
                                           <line x1="8" y1="3" x2="8" y2="7"></line>
                                           <line x1="4" y1="11" x2="20" y2="11"></line>
                                           <rect x="8" y="15" width="2" height="2"></rect>
                                        </svg>
        </span>
        <span class="nav-link-title">
            Schedule
        </span>
    </a>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'schedular:schedule' %}">Schedule</a>
        <a class="dropdown-item" href="{% url 'admins:shift-list' %}">Shifts</a>
    </div>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle"
       data-bs-toggle="dropdown"
       data-bs-auto-close="outside" role="button" aria-expanded="false">
        <span class="nav-link-icon d-md-none d-lg-inline-block">
            <svg xmlns="http://www.w3.org/2000/svg"
                 class="icon icon-tabler icon-tabler-stretching" width="24" height="24"
                 viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                 stroke-linecap="round" stroke-linejoin="round">
                                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                            <circle cx="16" cy="5" r="1"></circle>
                                            <path d="M5 20l5 -.5l1 -2"></path>
                                            <path d="M18 20v-5h-5.5l2.5 -6.5l-5.5 1l1.5 2"></path>
                                        </svg>
        </span>
        <span class="nav-link-title">TimeClock
        </span>
    </a>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'admins:time-clock' %}">Time Clock</a>
        <a class="dropdown-item" href="{% url 'admins:check-calls' %}">Check Calls</a>
    </div>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle"
       data-bs-toggle="dropdown"
       data-bs-auto-close="outside" role="button" aria-expanded="false">
        <span class="nav-link-icon d-md-none d-lg-inline-block">
            <svg xmlns="http://www.w3.org/2000/svg"
                 class="icon icon-tabler icon-tabler-user-check" width="24" height="24"
                 viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                 stroke-linecap="round" stroke-linejoin="round">
                 <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                 <circle cx="9" cy="7" r="4"></circle>
                <path d="M3 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"></path>
                <path d="M16 11l2 2l4 -4"></path>
            </svg>
        </span>
        <span class="nav-link-title">
            People
        </span>
    </a>
    <div class="dropdown-menu">
        <a class="dropdown-item"
           href="{% url 'admins:user-list' %}">Employees</a>
        <a class="dropdown-item" href="{% url 'admins:sub-contractor-list' %}">Sub Contractors</a>
    </div>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle"
       data-bs-toggle="dropdown"
       data-bs-auto-close="outside" role="button" aria-expanded="false">
        <span class="nav-link-icon d-md-none d-lg-inline-block">
            <svg xmlns="http://www.w3.org/2000/svg"
                 class="icon icon-tabler icon-tabler-users" width="24" height="24"
                 viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                 stroke-linecap="round" stroke-linejoin="round">
                                           <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                           <circle cx="9" cy="7" r="4"></circle>
                                           <path d="M3 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"></path>
                                           <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                                           <path d="M21 21v-2a4 4 0 0 0 -3 -3.85"></path>
                                        </svg>
        </span>
        <span class="nav-link-title">
            Client and Site
        </span>
    </a>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'admins:client-list' %}">Clients</a>
        <a class="dropdown-item" href="{% url 'admins:site-list' %}">Sites</a>
    </div>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'admins:absense-schedule' %}">
        <span class="nav-link-icon d-md-none d-lg-inline-block">
        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-accessible-off" width="24"
             height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round"
             stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
            <path d="M10 16.5l2 -3l2 3m-2 -3v-1.5m2.627 -1.376l.373 -.124m-6 0l2.231 .744"></path>
            <path d="M20.042 16.045a9 9 0 0 0 -12.087 -12.087m-2.318 1.677a9 9 0 1 0 12.725 12.73"></path>
            <path d="M12 8a0.5 .5 0 1 0 -.5 -.5"></path>
            <path d="M3 3l18 18"></path>
        </svg>
        </span>
        <span class="nav-link-title">
            Absences
        </span>
    </a>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle"
       data-bs-toggle="dropdown"
       data-bs-auto-close="outside" role="button" aria-expanded="false">
        <span class="nav-link-icon d-md-none d-lg-inline-block">
            <svg xmlns="http://www.w3.org/2000/svg"
                 class="icon icon-tabler icon-tabler-brand-asana" width="24" height="24"
                 viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                 stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <circle cx="12" cy="7" r="3"></circle>
                <circle cx="17" cy="16" r="3"></circle>
                <circle cx="7" cy="16" r="3"></circle>
            </svg>
        </span>
        <span class="nav-link-title">
            Management
        </span>
    </a>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'admins:country-list' %}">Countries</a>
        <a class="dropdown-item" href="{% url 'admins:position-list' %}">Positions</a>
        <a class="dropdown-item" href="{% url 'admins:report-type-list' %}">Report Categories</a>
        <a class="dropdown-item" href="{% url 'admins:department-list' %}">Departments</a>
        <a class="dropdown-item" href="{% url 'admins:absense-type-list' %}">Absense Types</a>
    </div>
</li>

templates/core/include/employee_header.html
{% load static %}

<li class="nav-item ">
    <a class="nav-link" href="{% url 'accounts:cross-auth' %}">
                                    <span class="nav-link-icon d-md-none d-lg-inline-block">
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             class="icon icon-tabler icon-tabler-home-bolt" width="24" height="24"
                                             viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                             stroke-linecap="round" stroke-linejoin="round">
                                             <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                             <path d="M19 10l-7 -7l-9 9h2v7a2 2 0 0 0 2 2h7.5"></path>
                                             <path d="M9 21v-6a2 2 0 0 1 2 -2h2c.661 0 1.248 .32 1.612 .815"></path>
                                             <path d="M19 14l-2 4h4l-2 4"></path>
                                        </svg>
                                    </span>
        <span class="nav-link-title">
                                        Dashboard
                                    </span>
    </a>
</li>

<li class="nav-item">
    <a class="nav-link"
       href="{% url 'employees:shift-list' %}">
                                    <span class="nav-link-icon d-md-none d-lg-inline-block">
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             class="icon icon-tabler icon-tabler-stretching" width="24" height="24"
                                             viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                             stroke-linecap="round" stroke-linejoin="round">
                                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                            <circle cx="16" cy="5" r="1"></circle>
                                            <path d="M5 20l5 -.5l1 -2"></path>
                                            <path d="M18 20v-5h-5.5l2.5 -6.5l-5.5 1l1.5 2"></path>
                                        </svg>
                                    </span>
        <span class="nav-link-title">
                                        Shifts
                                    </span>
    </a>
</li>

templates/core/include/header.html
{% load static %}

<header class="navbar navbar-expand-md navbar-light d-print-none">
    <div class="container-xl">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu"
                aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
            <a href="{% url 'accounts:login' %}">
                <img src="{% if site.logo %}{{ site.logo.url }}{% else %}https://placehold.co/100/{% endif %}" width="110"
                     height="32" alt="Tabler"
                     class="navbar-brand-image">
            </a>
        </h1>

        <div class="navbar-nav flex-row order-md-last">

            <div class="d-none d-md-flex">

                {# ENABLE DARK AND LIGHT MODES #}
                <a href="?theme=dark" class="nav-link px-0 hide-theme-dark" title="Enable dark mode"
                   data-bs-toggle="tooltip"
                   data-bs-placement="bottom">
                    <!-- Download SVG icon from http://tabler-icons.io/i/moon -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24"
                         viewBox="0 0 24 24"
                         stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round"
                         stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                        <path d="M12 3c.132 0 .263 0 .393 0a7.5 7.5 0 0 0 7.92 12.446a9 9 0 1 1 -8.313 -12.454z"/>
                    </svg>
                </a>
                <a href="?theme=light" class="nav-link px-0 hide-theme-light" title="Enable light mode"
                   data-bs-toggle="tooltip"
                   data-bs-placement="bottom">
                    <!-- Download SVG icon from http://tabler-icons.io/i/sun -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24"
                         viewBox="0 0 24 24"
                         stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round"
                         stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                        <circle cx="12" cy="12" r="4"/>
                        <path d="M3 12h1m8 -9v1m8 8h1m-9 8v1m-6.4 -15.4l.7 .7m12.1 -.7l-.7 .7m0 11.4l.7 .7m-12.1 -.7l-.7 .7"/>
                    </svg>
                </a>

                {# NOTIFICATIONS ----------------------------- #}
                {% include 'core/include/notifications.html' %}
                {# ------------------------------------------- #}

            </div>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown"
                   aria-label="Open user menu">
                    {% if request.user.profile_image %}
                        <span class="avatar avatar-sm"
                              style="background-image: url({{ request.user.profile_image.url }})">
                                </span>
                    {% else %}
                        <span class="avatar avatar-sm"
                              style="background-image: url({% static 'required/images/no-image.jpg' %})">
                                </span>
                    {% endif %}

                    <div class="d-none d-xl-block ps-2">
                        <div>{{ request.user.get_user_name }}</div>
                        <div class="mt-1 small text-muted">
                            {% if request.user.is_superuser %}
                                Administrator
                            {% elif request.user.is_staff %}
                                Staff User
                            {% elif request.user.is_employee %}
                                Employee
                            {% else %}
                                Undefined
                            {% endif %}
                        </div>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                    <a href="{% url 'accounts:user-change' %}" class="dropdown-item">Profile</a>
                    <a href="{% url 'accounts:user-password-change' %}" class="dropdown-item">Change Password</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
                </div>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="navbar-menu">
            <div class="d-flex flex-column flex-md-row flex-fill align-items-stretch align-items-md-center">
                <ul class="navbar-nav">

                    {% if request.user.is_superuser %}
                        {% include 'core/include/admin_header.html' %}
                    {% else %}
                        {% if request.user.is_staff %}
                            {% include 'core/include/staff_header.html' %}
                        {% else %}
                            {% include 'core/include/employee_header.html' %}
                        {% endif %}
                    {% endif %}

                </ul>
            </div>
        </div>
    </div>
</header>

templates/core/include/messages.html
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>

<script>
        {% if messages %}
            {% for message in messages %}
                toast_message("{{ message }}", "{{ message.tags }}")
            {% endfor %}
        {% endif %}

        function toast_message(message, message_tags) {
            Toastify({
                    text: message,
                    className: message_tags,
                    gravity: "top", // `top` or `bottom`
                    position: "center", // `left`, `center` or `right`
                    stopOnFocus: true,
                    duration: 10000,
                    close: true,
                    style: {
                        background: get_message_color(message_tags),
                    }
                }).showToast();
        }

        function get_message_color(value) {
            if (value === 'info') {
                return "#337ab7";
            } else if (value === 'warning') {
                return "#8a6d3b";
            } else if (value === 'error') {
                return "#a94442";
            } else if (value === 'success') {
                return "#3c763d";
            } else {
                return "#31708f";
            }
        }
</script>

templates/core/include/notifications.html
{% load static %}
{% load notifications_tags %}

<div class="nav-item dropdown d-none d-md-flex me-3">
    <a href="#" class="nav-link px-0" data-bs-toggle="dropdown" tabindex="-1"
       aria-label="Show notifications">

        <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24"
             viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
             stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
            <path d="M10 5a2 2 0 0 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3h-16a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6"/>
            <path d="M9 17v1a3 3 0 0 0 6 0v-1"/>
        </svg>

        {% notifications_unread as unread_count %}
        {% if unread_count %}
            <span class="badge bg-red">{{ unread_count }}</span>
        {% endif %}

    </a>

    <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-end dropdown-menu-card" style="overflow: auto;max-height: 600px;">
        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h3 class="card-title mb-0">
                    Last updates
                </h3>

                {# TODO: notifications issue - like it doesn't loads all the notifications #}
                {% if unread_count %}
                    <button class="btn btn-sm rounded text-secondary p-2" onclick="unread_all_notifications()">
                        <i class="fa fa-paint-brush"></i> clear
                    </button>
                {% endif %}
            </div>
            <div class="list-group list-group-flush list-group-hoverable" id="notify_me_now">
            </div>
        </div>
    </div>
</div>

templates/core/include/staff_header.html
{% load static %}

<li class="nav-item ">
    <a class="nav-link" href="{% url 'accounts:cross-auth' %}">
                                    <span class="nav-link-icon d-md-none d-lg-inline-block">
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             class="icon icon-tabler icon-tabler-home-bolt" width="24" height="24"
                                             viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                             stroke-linecap="round" stroke-linejoin="round">
                                             <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                             <path d="M19 10l-7 -7l-9 9h2v7a2 2 0 0 0 2 2h7.5"></path>
                                             <path d="M9 21v-6a2 2 0 0 1 2 -2h2c.661 0 1.248 .32 1.612 .815"></path>
                                             <path d="M19 14l-2 4h4l-2 4"></path>
                                        </svg>
                                    </span>
        <span class="nav-link-title">
                                        Dashboard
                                    </span>
    </a>
</li>