core/urls.py
import notifications
from django.contrib import admin
from django.shortcuts import render, redirect
from django.views.static import serve
from django.urls import path, include, re_path

from .settings import MEDIA_ROOT, STATIC_ROOT, ENVIRONMENT

""" __ ERROR HANDLERS AND VIEWS __ """


def handler404(request, *args, **kwargs):
    return render(request, "404.html")


def handler500(request, *args, **kwargs):
    return render(request, "500.html")


def home(request, *args, **kwargs):
    return redirect('accounts:login')


handler404 = handler404
handler500 = handler500

""" __ URLS __ """

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', home, name='home'),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('a/', include('src.administration.admins.urls', namespace='admins')),
    path('c/', include('src.administration.employees.urls', namespace='employees')),
    path('scheduler/', include('src.services.schedular.urls', namespace='scheduler')),
]

urlpatterns += [
    path('accounts/', include('allauth.urls')),
    path('inbox/notifications/', include('notifications.urls', namespace='notifications')),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
]

""" __ DEBUG URLS __ """

if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

src/administration/employees/urls.py
from django.urls import path
from .views import (
    DashboardView, ShiftListView, ShiftDetailView
)

app_name = 'employees'
urlpatterns = [

    path('', DashboardView.as_view(), name="dashboard"),
    path('my/shift/', ShiftListView.as_view(), name="shift-list"),
    path('my/shift/<int:pk>/', ShiftDetailView.as_view(), name="shift-detail"),

]

src/administration/admins/models.py
from datetime import datetime, timedelta

from colorfield.fields import ColorField
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model
from src.accounts.models import Employee
from faker import Faker

User = get_user_model()
fake = Faker()


class Position(models.Model):
    name = models.CharField(max_length=255)
    card_color = ColorField(default='#FFFFFF')
    charge_rate = models.FloatField()
    pay_rate = models.FloatField()

    is_active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-id']
        verbose_name_plural = "Positions"

    def __str__(self):
        return str(self.name)

    @classmethod
    def fake(cls, loop=10):
        print()
        print("- POSITIONS: build")
        for x in range(loop):
            Position.objects.create(
                name=fake.job(), card_color="#FFFFFF", charge_rate=fake.random_number(digits=3),
                pay_rate=fake.random_number(digits=3)
            )
            print(f"---- Position: {x} faked.")
        print("- END ")
        print()


class Department(models.Model):
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-id']
        verbose_name_plural = "Departments"

    def __str__(self):
        return str(self.name)

    @classmethod
    def fake(cls, loop=10):
        print()
        print("- DEPARTMENT: build")
        for x in range(loop):
            Department.objects.create(
                name=fake.job(), is_active=True
            )
            print(f"---- department: {x} faked.")
        print("- END ")
        print()


class Country(models.Model):
    name = models.CharField(max_length=255, unique=True)
    language = models.CharField(max_length=50, null=True, blank=True)
    currency = models.CharField(max_length=50, null=True, blank=True)
    time_zone = models.CharField(max_length=100, null=True, blank=True)
    phone_code = models.CharField(max_length=50, null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "Countries"
        ordering = ['-id']

    def __str__(self):
        return self.name

    @classmethod
    def fake(cls, loop=10):
        print()
        print("- COUNTRY: build")
        for x in range(loop):
            Country.objects.create(
                name=fake.country()
            )
            print(f"---- country: {x} faked.")
        print("- END ")
        print()


class Client(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=15, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)

    registration_number = models.CharField(null=True, blank=True, max_length=255)
    vat_number = models.CharField(null=True, blank=True, max_length=255)
    website = models.URLField(null=True, blank=True)
    address = models.CharField(max_length=1000, null=True, blank=True)
    city = models.CharField(max_length=1000, null=True, blank=True, verbose_name="City/Town")
    Post_code = models.CharField(max_length=255, null=True, blank=True)
    country = models.ForeignKey(Country, null=True, blank=True, on_delete=models.SET_NULL)

    is_active = models.BooleanField(
        default=False,
        help_text="Is this client is active"
    )

    class Meta:
        ordering = ['id']
        verbose_name_plural = "Clients"

    def __str__(self):
        return str(self.name)

    def get_sites(self):
        return Site.objects.filter(client=self)

    @classmethod
    def fake(cls, loop=10):
        print()
        print("- CLIENTS: build")
        for x in range(loop):
            Client.objects.create(
                name=fake.bs(), registration_number=fake.isbn10()
            )
            print(f"---- Client: {x} faked.")
        print("- END ")
        print()


class ReportType(models.Model):
    name = models.CharField(max_length=255)
    icon = models.CharField(max_length=255)

    class Meta:
        ordering = ['id']
        verbose_name_plural = "Report Types"

    def __str__(self):
        return str(self.name)

    @classmethod
    def fake(cls, loop=10):
        print()
        print("- REPORT TYPE: build")
        for x in range(loop):
            ReportType.objects.create(
                name=fake.bs(), icon="fa fa-icon"
            )
            print(f"---- Report Type: {x} faked.")
        print("- END ")
        print()


class Site(models.Model):
    CHECK_CALLS_ENABLE_TYPE = (
        ('yes', 'Yes'),
        ('no', 'No'),
    )
    site_id = models.CharField(max_length=1000, null=True, blank=True)
    name = models.CharField(max_length=255)

    company_name = models.CharField(max_length=255, null=True, blank=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    geo_fencing_range = models.CharField(
        max_length=1000, help_text="What is the maximum distance an employee can "
                                   "be from their designated location when starting their shift? in meters."
    )

    notes = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    address = models.CharField(max_length=255)
    city = models.CharField(max_length=255, verbose_name='City/Town')
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=True)

    longitude = models.FloatField(null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)

    check_calls_enabled = models.BooleanField(
        default=False, help_text="Enabling check calls will allow the system to track employee work during their shift."
    )
    is_active = models.BooleanField(default=False)

    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['id']
        verbose_name_plural = "Sites"

    def __str__(self):
        return str(self.name)

    @classmethod
    def fake(cls, loop=10):
        print()
        print("- SITES: build")
        for x in range(loop):
            Site.objects.create(
                site_id=fake.random_number(digits=3, fix_len=False),
                latitude=fake.random_number(digits=3, fix_len=False),
                longitude=fake.random_number(digits=3, fix_len=False),
                name=fake.isbn10(),
                client=Client.objects.order_by('?').first(),
                notes=fake.paragraph(nb_sentences=3),
                description=fake.paragraph(nb_sentences=3),
                company_name=fake.bs(),
                address=fake.address(),
                city=fake.city(),
                country=Country.objects.order_by('?').first(),
                geo_fencing_range=fake.random_number(digits=5, fix_len=False),
            )
            print(f"---- Site: {x} faked.")
        print("- END ")
        print()


class Shift(models.Model):
    JOB_TYPE_CHOICE = (
        ('o', 'Open'),
        ('p', 'Pattern'),
    )
    REPEAT_POLICY_TYPE = (
        ('r', 'Regular'),
        ('w', 'Weekly repeat'),
        ('d', 'Selected Dates'),
    )
    job_type = models.CharField(default='o', choices=JOB_TYPE_CHOICE, max_length=1)

    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    start_time = models.TimeField()
    end_time = models.TimeField()
    site = models.ForeignKey(Site, on_delete=models.CASCADE)

    position = models.ForeignKey(Position, on_delete=models.SET_NULL, null=True, blank=True)
    employee = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True, blank=True, related_name="employee")

    # quantity = models.PositiveIntegerField(default=1)
    pay_rate = models.FloatField(default=0)
    charge_rate = models.FloatField(default=0)
    extra_charges = models.FloatField(default=0)
    week_days = models.CharField(max_length=7, default='', blank=True, editable=False)

    repeat_policy = models.CharField(max_length=1, default='r', choices=REPEAT_POLICY_TYPE, null=True, blank=False)

    class Meta:
        ordering = ['id']
        verbose_name_plural = "Shifts"

    def __str__(self):
        return str(self.pk)

    def save(self, *args, **kwargs):
        """
        LOGIC 1 :: if job_type == open >> set last_date to first_date
        """
        if self.job_type == 'o' or not self.end_date:
            self.end_date = self.start_date
        super(Shift, self).save(*args, **kwargs)

    def get_shifts(self):
        return ShiftDay.objects.filter(shift=self)

    def get_week_shifts_status(self):
        llist = []
        [llist.append(True) if str(x) in self.week_days else llist.append(False) for x in range(7)]
        return llist


class ShiftDay(models.Model):
    shift = models.ForeignKey(Shift, on_delete=models.CASCADE)

    clock_in = models.TimeField(null=True, blank=True)
    clock_out = models.TimeField(null=True, blank=True)
    employee = models.ForeignKey(
        Employee, on_delete=models.SET_NULL, null=True, blank=True, related_name="employee_for_shift"
    )

    shift_date = models.DateField()
    shift_end_date = models.DateField()

    shift_time = models.TimeField(null=True, blank=True)
    shift_end_time = models.TimeField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Shift Days"

    def __str__(self):
        return str(self.pk)

    def save(self, *args, **kwargs):
        """
        :start       --- get start datetime from (shift_date + shift_start_time)
        :end         --- get start datetime from (shift_date + shift_end_time)
        :total hours --- end - start
        """

        # ON CREATE :: shift_times and shift_dates are equal to parent
        if self._state.adding and self.shift_date:
            self.shift_time = self.shift.start_time
            self.shift_end_time = self.shift.end_time
            self.employee = self.shift.employee

src/administration/employees/views.py
import datetime

from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, ListView, DetailView, UpdateView

from src.accounts.decorators import employee_protected
from src.administration.admins.models import Shift


@method_decorator(employee_protected, name='dispatch')
class DashboardView(TemplateView):
    template_name = 'employees/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['shifts'] = Shift.objects.filter(employee__user=self.request.user)
        return context


@method_decorator(employee_protected, name='dispatch')
class ShiftListView(ListView):
    template_name = 'employees/shift_list.html'

    def get_queryset(self):
        return Shift.objects.filter(employee__user=self.request.user)


@method_decorator(employee_protected, name='dispatch')
class ShiftDetailView(DetailView):
    model = Shift
    template_name = 'employees/shift_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ShiftDetailView, self).get_context_data(**kwargs)
        context['current_date'] = datetime.date.today()
        return context

src/administration/employees/templates/employees/dashboard.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_subtitle %}
    Dashboard
{% endblock %}

{% block base_subhead_heading %} Employee &rAarr; Dashboard{% endblock %}
{% block base_subhead_paragraph %}Detailed down employee dashboard view{% endblock %}



{% block base_content %}

    <div class="row">
        <div class="col-sm-12">

            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Your shifts</h3>
                </div>
                {% if object_list %}

                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead class="thead-light">
                            <tr>
                                <th>Type</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th>Start Time</th>
                                <th>End Time</th>
                                <th>Client</th>
                                <th>Days</th>
                                <th>-</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for object in object_list %}
                                <tr>
                                    <td>
                                        {% if object.get_job_type_display == "Pattern" %}
                                            <span class="badge bg-purple-lt">{{ object.get_job_type_display }}</span>
                                        {% else %}
                                            <span class="badge bg-teal-lt">{{ object.get_job_type_display }}</span>
                                        {% endif %}
                                    </td>
                                    <td>{{ object.start_date }}</td>
                                    <td>{{ object.end_date }}</td>
                                    <td>{{ object.start_time|date:"G:i" }}</td>
                                    <td>{{ object.end_time|date:"G:i" }}</td>
                                    <td>
                                        <a href="#">
                                            {{ object.client.name }}
                                        </a>
                                    </td>
                                    <td>{{ object.shiftday_set.count }}</td>
                                    <th>
                                        <a href="{% url 'employees:shift-detail' object.pk %}">
                                            <svg xmlns="http://www.w3.org/2000/svg"
                                                 class="icon icon-tabler icon-tabler-eye" width="24" height="24"
                                                 viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                                 stroke-linecap="round" stroke-linejoin="round">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                                <circle cx="12" cy="12" r="2"></circle>
                                                <path d="M22 12c-2.667 4.667 -6 7 -10 7s-7.333 -2.333 -10 -7c2.667 -4.667 6 -7 10 -7s7.333 2.333 10 7"></path>
                                            </svg>
                                        </a>
                                    </th>
                                </tr>
                            {% endfor %}


                            </tbody>
                        </table>
                    </div>

                {% else %}
                    <div class="card-body">
                        <p class="text-danger"><b>No shifts available</b></p>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

src/administration/employees/templates/employees/shift_list.html
{% extends 'core/base.html' %}
{% load static %}
{% load custom_tags %}

{% block base_subtitle %} Shifts{% endblock %}
{% block base_subhead_heading %} Shifts &rAarr; List{% endblock %}
{% block base_subhead_paragraph %}List of all available shifts{% endblock %}

{% block base_content %}

    <div class="row">

        <div class="col-12">
            <div class="card">
                {% if object_list %}

                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead class="thead-light">
                            <tr>
                                <th>Type</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th>Start Time</th>
                                <th>End Time</th>
                                <th>Site</th>
                                <th>Days</th>
                                <th>-</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for object in object_list %}
                                <tr>
                                    <td>
                                        {% if object.get_job_type_display == "Pattern" %}
                                            <span class="badge bg-purple-lt">{{ object.get_job_type_display }}</span>
                                        {% else %}
                                            <span class="badge bg-teal-lt">{{ object.get_job_type_display }}</span>
                                        {% endif %}
                                    </td>
                                    <td>{{ object.start_date }}</td>
                                    <td>{{ object.end_date }}</td>
                                    <td>{{ object.start_time|date:"G:i" }}</td>
                                    <td>{{ object.end_time|date:"G:i" }}</td>
                                    <td>
                                        <a href="#">
                                            {{ object.site.name }}
                                        </a>
                                    </td>
                                    <td>{{ object.shiftday_set.count }}</td>
                                    <th>
                                        <a href="{% url 'employees:shift-detail' object.pk %}">
                                            <svg xmlns="http://www.w3.org/2000/svg"
                                                 class="icon icon-tabler icon-tabler-eye" width="24" height="24"
                                                 viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                                 stroke-linecap="round" stroke-linejoin="round">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                                <circle cx="12" cy="12" r="2"></circle>
                                                <path d="M22 12c-2.667 4.667 -6 7 -10 7s-7.333 -2.333 -10 -7c2.667 -4.667 6 -7 10 -7s7.333 2.333 10 7"></path>
                                            </svg>
                                        </a>
                                    </th>
                                </tr>
                            {% endfor %}


                            </tbody>
                        </table>
                    </div>

                {% else %}
                    <div class="card-body">
                        <p class="text-danger"><b>No shifts available</b></p>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}