core/urls.py
import notifications
from django.contrib import admin
from django.shortcuts import render, redirect
from django.views.static import serve
from django.urls import path, include, re_path

from .settings import MEDIA_ROOT, STATIC_ROOT, ENVIRONMENT

""" __ ERROR HANDLERS AND VIEWS __ """


def handler404(request, *args, **kwargs):
    return render(request, "404.html")


def handler500(request, *args, **kwargs):
    return render(request, "500.html")


def home(request, *args, **kwargs):
    return redirect('accounts:login')


handler404 = handler404
handler500 = handler500

""" __ URLS __ """

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', home, name='home'),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('a/', include('src.administration.admins.urls', namespace='admins')),
    path('c/', include('src.administration.employees.urls', namespace='employees')),
    path('scheduler/', include('src.services.schedular.urls', namespace='scheduler')),
]

urlpatterns += [
    path('accounts/', include('allauth.urls')),
    path('inbox/notifications/', include('notifications.urls', namespace='notifications')),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
]

""" __ DEBUG URLS __ """

if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

src/administration/admins/urls.py
from django.urls import path, include
from .views import (
    DashboardView, TimeClockView, CheckCallsView,
    PositionListView, PositionDeleteView, PositionCreateView, PositionUpdateView,
    UserPasswordResetView, UserListView, UserStaffCreateView, UserEmployeeCreateView, UserUpdateView, UserDeleteView,
    ClientListView, ClientDetailView, ClientUpdateView, ClientDeleteView, ClientCreateView,
    SiteListView, SiteDetailView, SiteUpdateView, SiteDeleteView, SiteCreateView,
    ReportTypeListView, ReportTypeUpdateView, ReportTypeDeleteView, ReportTypeCreateView,
    ShiftDayUpdateView, ShiftDayDeleteView,
    ShiftCreateView, ShiftUpdateView, ShiftDeleteView, UserDetailView,
    ShiftListView, ShiftDetailView, ShiftCustomCreateView,
    CountryListView, CountryCreateView, CountryUpdateView, CountryDeleteView, SubContractorListView,
    SubContractorCreateView, SubContractorUpdateView, SubContractorDeleteView, SubContractorDetailView,
    DepartmentListView, DepartmentCreateView, DepartmentUpdateView, DepartmentDeleteView,

    AbsenseTypeListView, AbsenseTypeCreateView, AbsenseTypeDeleteView, AbsenseTypeUpdateView, AbsenseScheduleView,
    UserEmployeeInviteCreateView
)

app_name = 'admins'
urlpatterns = [
    path('', DashboardView.as_view(), name="dashboard"),
    path('time-clock/', TimeClockView.as_view(), name="time-clock"),
    path('absenses/', AbsenseScheduleView.as_view(), name="absense-schedule"),
    path('check-calls/', CheckCallsView.as_view(), name="check-calls"),
]

urlpatterns += [
    path('position/', PositionListView.as_view(), name='position-list'),
    path('position/add/', PositionCreateView.as_view(), name='position-add'),
    path('position/<int:pk>/change/', PositionUpdateView.as_view(), name='position-update'),
    path('position/<int:pk>/delete/', PositionDeleteView.as_view(), name='position-delete'),
]

urlpatterns += [
    path('country/', CountryListView.as_view(), name='country-list'),
    path('country/add/', CountryCreateView.as_view(), name='country-add'),
    path('country/<int:pk>/change/', CountryUpdateView.as_view(), name='country-update'),
    path('country/<int:pk>/delete/', CountryDeleteView.as_view(), name='country-delete'),
]

urlpatterns += [
    path('department/', DepartmentListView.as_view(), name='department-list'),
    path('department/add/', DepartmentCreateView.as_view(), name='department-add'),
    path('department/<int:pk>/change/', DepartmentUpdateView.as_view(), name='department-update'),
    path('department/<int:pk>/delete/', DepartmentDeleteView.as_view(), name='department-delete'),
]

urlpatterns += [
    path('shift/', ShiftListView.as_view(), name='shift-list'),
    path('shift/add/', ShiftCreateView.as_view(), name='shift-add'),
    path('shift/<int:pk>/', ShiftDetailView.as_view(), name='shift-detail'),
    path('shift/<int:pk>/change/', ShiftUpdateView.as_view(), name='shift-update'),
    path('shift/<int:pk>/delete/', ShiftDeleteView.as_view(), name='shift-delete'),
]

urlpatterns += [
    path('shift-day/<int:pk>/change/', ShiftDayUpdateView.as_view(), name='shift-day-update'),
    path('shift-day/<int:pk>/delete/', ShiftDayDeleteView.as_view(), name='shift-day-delete'),
]

urlpatterns += [
    path('client/', ClientListView.as_view(), name='client-list'),
    path('client/add/', ClientCreateView.as_view(), name='client-add'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client-detail'),
    path('client/<int:pk>/change/', ClientUpdateView.as_view(), name='client-update'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client-delete'),
]

urlpatterns += [
    path('site/', SiteListView.as_view(), name='site-list'),
    path('site/add/', SiteCreateView.as_view(), name='site-add'),
    path('site/<int:pk>/', SiteDetailView.as_view(), name='site-detail'),
    path('site/<int:pk>/change/', SiteUpdateView.as_view(), name='site-update'),
    path('site/<int:pk>/delete/', SiteDeleteView.as_view(), name='site-delete'),
]

urlpatterns += [
    path('report-type/', ReportTypeListView.as_view(), name='report-type-list'),
    path('report-type/add/', ReportTypeCreateView.as_view(), name='report-type-add'),
    path('report-type/<int:pk>/change/', ReportTypeUpdateView.as_view(), name='report-type-update'),
    path('report-type/<int:pk>/delete/', ReportTypeDeleteView.as_view(), name='report-type-delete'),
]

urlpatterns += [
    path('absense-type/', AbsenseTypeListView.as_view(), name='absense-type-list'),
    path('absense-type/add/', AbsenseTypeCreateView.as_view(), name='absense-type-add'),
    path('absense-type/<int:pk>/change/', AbsenseTypeUpdateView.as_view(), name='absense-type-update'),
    path('absense-type/<int:pk>/delete/', AbsenseTypeDeleteView.as_view(), name='absense-type-delete'),
]

urlpatterns += [
    path('sub-contractor/', SubContractorListView.as_view(), name='sub-contractor-list'),
    path('sub-contractor/add/', SubContractorCreateView.as_view(), name='sub-contractor-add'),
    path('sub-contractor/<int:pk>/', SubContractorDetailView.as_view(), name='sub-contractor-detail'),
    path('sub-contractor/<int:pk>/change/', SubContractorUpdateView.as_view(), name='sub-contractor-update'),
    path('sub-contractor/<int:pk>/delete/', SubContractorDeleteView.as_view(), name='sub-contractor-delete'),
]

urlpatterns += [
    path('user/', UserListView.as_view(), name='user-list'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/<int:pk>/change/', UserUpdateView.as_view(), name='user-update'),
    path('user/<int:pk>/delete/', UserDeleteView.as_view(), name='user-delete'),
    path('user/staff/add/', UserStaffCreateView.as_view(), name='user-staff-add'),
    path('user/employee/add/', UserEmployeeCreateView.as_view(), name='user-employee-add'),
    path('user/employee/invite/add/', UserEmployeeInviteCreateView.as_view(), name='user-employee-invite-add'),
    path('user/<int:pk>/reset/password/', UserPasswordResetView.as_view(), name='user-password-reset'),
]

urlpatterns += [
    path('api/', include('src.administration.admins.admins-api.urls', namespace='admins-api')),
    path('json/', include('src.administration.admins.admins-json.urls', namespace='admins-json'))
]

src/services/schedular/urls.py
from django.urls import path

from .views import (
    ScheduleView, ShiftAddModelView
)

app_name = "schedular"
urlpatterns = [
    path('', ScheduleView.as_view(), name='schedule'),
    path('model/shift/add/', ShiftAddModelView.as_view(), name='model_shift_add'),
]

src/administration/admins/templates/admins/include/navbar_left.html
{% if request.user.is_superuser %}
    <div class="left-sidenav">
        <ul class="metismenu left-sidenav-menu" id="side-nav">
            <li class="menu-title">General</li>

            <li>
                <a href="{% url 'admins:dashboard' %}">
                    <i class="mdi mdi-view-dashboard"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <li class="menu-title">SHIFTS AND SCHEDULE</li>
            <li>
                <a href="{% url 'admins:schedule' %}">
                    <i class="fa fa-notes-medical"></i>
                    <span>Schedule</span>
                </a>
            </li>
            <li>
                <a href="{% url 'admins:shift-list' %}">
                    <i class="fa fa-calendar-check"></i>
                    <span>Shifts</span>
                </a>
            </li>
            <li>
                <a href="{% url 'admins:time-clock' %}?shift_date=today&shift__employee__user__username=">
                    <i class="fa fa-clock"></i>
                    <span>Time Clock</span>
                </a>
            </li>


            <li class="menu-title">REPORTS</li>
            <li>
                <a href="{% url 'admins:reports' %}">
                    <i class="fa fa-chart-line"></i>
                    <span>Reports</span>
                </a>
            </li>
            <li>
                <a href="{% url 'admins:shift-notes' %}">
                    <i class="fa fa-paragraph"></i>
                    <span>Shift Notes</span>
                </a>
            </li>
            <li>
                <a href="{% url 'admins:charges-break' %}">
                    <i class="mdi mdi-cash"></i>
                    <span>charges Break</span>
                </a>
            </li>
            <li>
                <a href="{% url 'admins:pay-run-report' %}">
                    <i class="fa fa-edit"></i>
                    <span>Pay Run Report</span>
                </a>
            </li>
            <li>
                <a href="{% url 'admins:health' %}">
                    <i class="mdi mdi-medical-bag"></i>
                    <span>Health</span>
                </a>
            </li>


            <li class="menu-title">USERS MANAGEMENT</li>
            <li>
                <a href="{% url 'admins:user-list' %}">
                    <i class="fa fa-user-cog"></i>
                    <span>Employees</span>
                </a>
            </li>
            <li>
                <a href="{% url 'admins:client-list' %}">
                    <i class="fa fa-users"></i>
                    <span>Clients</span>
                </a>
            </li>
            <li>
                <a href="{% url 'admins:site-list' %}">
                    <i class="fa fa-building"></i>
                    <span>Sites</span>
                </a>
            </li>

            <li class="menu-title">SETTINGS</li>
            <li>
                <a href="{% url 'admins:position-list' %}">
                    <i class="fa fa-user-cog"></i>
                    <span>Positions</span>
                </a>
            </li>
            <li>
                <a href="{% url 'admins:country-list' %}">
                    <i class="fa fa-globe"></i>
                    <span>Countries</span>
                </a>
            </li>
            <li>
                <a href="{% url 'admins:report-type-list' %}">
                    <i class="fa fa-chart-line"></i>
                    <span>Reports Types</span>
                </a>
            </li>

        </ul>
    </div>
{% else %}
    <div class="left-sidenav">
        <ul class="metismenu left-sidenav-menu" id="side-nav">

            <li>
                <a href="{% url 'employees:dashboard' %}">
                    <i class="mdi mdi-view-dashboard"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li>
                <a href="{% url 'employees:shift-list' %}">
                    <i class="mdi mdi-view-array"></i>
                    <span>Shifts</span>
                </a>
            </li>
        </ul>
    </div>
{% endif %}

src/administration/admins/templates/admins/include/user_detail_tabs.html
{% load static %}

{# TABS AREA #}
<div class="row mt-4">
    <div class="col-sm-12">

        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs nav-fill" data-bs-toggle="tabs" role="tablist">
                    <li class="nav-item" role="presentation">
                        <a href="#tabs-details" class="nav-link active" data-bs-toggle="tab"
                           aria-selected="true"
                           role="tab">
                            <i class="fa fa-home"></i>&nbsp;Details
                        </a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a href="#tabs-employment" class="nav-link " data-bs-toggle="tab" aria-selected="false"
                           role="tab" tabindex="-1">
                            <i class="fa fa-briefcase"></i>&nbsp;Employment
                        </a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a href="#tabs-expertise" class="nav-link " data-bs-toggle="tab" aria-selected="false"
                           role="tab" tabindex="-1">
                            <i class="fa fa-hammer"></i>&nbsp;Expertise
                        </a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a href="#tabs-background" class="nav-link " data-bs-toggle="tab" aria-selected="false"
                           role="tab" tabindex="-1">
                            <i class="fa fa-history"></i>&nbsp;Background
                        </a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a href="#tabs-hal" class="nav-link " data-bs-toggle="tab" aria-selected="false"
                           role="tab" tabindex="-1">
                            <i class="fa fa-heart"></i>&nbsp;Health and Look
                        </a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a href="#tabs-docs" class="nav-link " data-bs-toggle="tab" aria-selected="false"
                           role="tab" tabindex="-1">
                            <i class="fa fa-pagelines"></i>&nbsp;Docs
                        </a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a href="#tabs-settings" class="nav-link " data-bs-toggle="tab" aria-selected="false"
                           role="tab" tabindex="-1">
                            <i class="fa fa-cogs"></i>
                        </a>
                    </li>

                </ul>
            </div>
            <div class="card-body">
                <div class="tab-content">

                    {# TAB1: details #}
                    {% include 'admins/include/user_details_tabs_details.html' %}

                    {# TAB2: employment #}
                    {% include 'admins/include/user_details_tabs_employment.html' %}

                    {# TAB2: expertise #}
                    {% include 'admins/include/user_details_tabs_expertise.html' %}

                    {# TAB2: Background #}
                    {% include 'admins/include/user_details_tabs_background.html' %}

                    {# TAB2: HAL #}
                    {% include 'admins/include/user_details_tabs_hal.html' %}

                    {# TAB2: DOCS #}
                    {% include 'admins/include/user_details_tabs_docs.html' %}

                    {# TAB2: SEttings #}
                    {% include 'admins/include/user_details_tabs_settings.html' %}

                </div>
            </div>
        </div>

    </div>
</div>

src/administration/admins/templates/admins/include/user_details_tabs_background.html
{% load static %}
{% load crispy_forms_tags %}

<div class="tab-pane" id="tabs-background" role="tabpanel">
    {# EMPLOYMENT #}
    <div class="mb-4">
        <div class="mb-2">
            <button class="btn btn-primary" id="employee_emp_add_btn">
                + Add Employment
            </button>
        </div>
        {% if employee_employments %}
            <div class="table-responsive">
                <table class="table table-sm table-hover">
                    <thead class="thead-light">
                    <tr>
                        <th>Employer</th>
                        <th>Position</th>
                        <th>Description</th>
                        <th>Contact Person</th>
                        <th>Contact Phone</th>
                        <th>Date From</th>
                        <th>Date To</th>
                        <th>Reason For Leaving</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for oobject in employee_employments %}
                        <tr>
                            <td>{{ oobject.employer }}</td>
                            <td>{{ oobject.position }}</td>
                            <td>{{ oobject.description }}</td>
                            <td>{{ oobject.contact_person }}</td>
                            <td>{{ oobject.contact_phone }}</td>
                            <td>{{ oobject.date_form }}</td>
                            <td>{{ oobject.date_to }}</td>
                            <td>{{ oobject.reason_for_leaving }}</td>
                            <td>
                                <button type="button" id="employee_emp_delete_btn"
                                        data-action="{% url 'admins:admins-json:employee_employment_delete' oobject.pk %}" data-param=""
                                        data-method="GET"
                                        class="btn btn-link btn-sm text-danger">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        {% else %}
            <div>
                <p class="mb-0 text-danger"><b>Information not available</b></p>
            </div>
        {% endif %}
    </div>

    {# EDUCATION #}
    <div class="mb-4">
        <div class="mb-2">
            <button class="btn btn-primary" id="employee_education_add_btn">
                + Add Education
            </button>
        </div>
        {% if employee_educations %}
            <div class="table-responsive">
                <table class="table table-sm table-hover">
                    <thead class="thead-light">
                    <tr>
                        <th>Institution</th>
                        <th>Speciality</th>
                        <th>Degree Obtained</th>
                        <th>City</th>
                        <th>Country</th>
                        <th>Date Form</th>
                        <th>Dte To</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for oobject in employee_educations %}
                        <tr>
                            <td>{{ oobject.institution }}</td>
                            <td>{{ oobject.speciality }}</td>
                            <td>{{ oobject.degree_obtained }}</td>
                            <td>{{ oobject.city }}</td>
                            <td>{{ oobject.country }}</td>
                            <td>{{ oobject.date_form }}</td>
                            <td>{{ oobject.date_to }}</td>
                            <td>
                                <button type="button" id="employee_education_delete_btn"
                                        data-action="{% url 'admins:admins-json:employee_education_delete' oobject.pk %}" data-param=""
                                        data-method="GET"
                                        class="btn btn-link btn-sm text-danger">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        {% else %}
            <div>
                <p class="mb-0 text-danger"><b>Information not available</b></p>
            </div>
        {% endif %}
    </div>
</div>

<div class="modal" tabindex="-1" id="employee_education_add_model">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title">Add Education</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form method="post">
                    {% csrf_token %}
                    {% crispy employee_educations_form %}
                </form>
            </div>

            <div class="modal-footer text-left">
                <button type="button" id="employee_education_submit_btn"
                        data-action="{% url 'admins:admins-json:employee_education_add' employee.pk %}" data-param=""
                        data-method="POST"
                        class="btn btn-success me-auto">
                    <i class="fa fa-check"></i>&nbsp;Submit
                </button>
            </div>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" id="employee_emp_add_model">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title">Add Employment</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form method="post">
                    {% csrf_token %}
                    {% crispy employee_employments_form %}
                </form>
            </div>

            <div class="modal-footer text-left">
                <button type="button" id="employee_emp_submit_btn"
                        data-action="{% url 'admins:admins-json:employee_employment_add' employee.pk %}" data-param=""
                        data-method="POST"
                        class="btn btn-success me-auto">
                    <i class="fa fa-check"></i>&nbsp;Submit
                </button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {

        $('#employee_education_add_model #id_date_form').datetimepicker({
            format: 'Y-m-d',
            timepicker: false,
        });
        $('#employee_education_add_model #id_date_to').datetimepicker({
            format: 'Y-m-d',
            timepicker: false,
        });
        $('#employee_emp_add_model #id_date_form').datetimepicker({
            format: 'Y-m-d',
            timepicker: false,
        });
        $('#employee_emp_add_model #id_date_to').datetimepicker({
            format: 'Y-m-d',
            timepicker: false,
        });

        {# QUALIFICATION AREA --------------------------------------------------------------------------------------- #}

        let employee_education_add_btn = $('body #employee_education_add_btn')
        let employee_education_delete_btn = $('body #employee_education_delete_btn')
        let employee_education_submit_btn = $('body #employee_education_submit_btn')
        let employee_education_add_model = $('body #employee_education_add_model')
        let employee_education_add_form = employee_education_add_model.find('form')
        employee_education_add_btn.click(function () {
            employee_education_add_model.modal('show')
        });
        employee_education_submit_btn.click(function () {
            $.ajax({
                url: $(this).data('action'),
                type: $(this).data('method'),
                data: employee_education_add_form.serialize(),
                success: function (data) {
                    if (!(data['success'])) {
                        employee_education_add_form.html(data['form_html']);
                    } else {
                        location.reload();
                    }
                },
                error: function () {
                    employee_education_add_form.find('.error-message').show()
                }
            });
        });
        employee_education_delete_btn.click(function () {
            $.ajax({
                url: $(this).data('action'),
                type: $(this).data('method'),
                success: function (data) {
                    location.reload();
                },
                error: function (error) {
                    console.log(error)
                }
            });
        });

        let employee_emp_add_btn = $('body #employee_emp_add_btn')
        let employee_emp_delete_btn = $('body #employee_emp_delete_btn')
        let employee_emp_submit_btn = $('body #employee_emp_submit_btn')
        let employee_emp_add_model = $('body #employee_emp_add_model')
        let employee_emp_add_form = employee_emp_add_model.find('form')
        employee_emp_add_btn.click(function () {
            employee_emp_add_model.modal('show')
        });
        employee_emp_submit_btn.click(function () {
            $.ajax({
                url: $(this).data('action'),
                type: $(this).data('method'),
                data: employee_emp_add_form.serialize(),
                success: function (data) {
                    if (!(data['success'])) {
                        employee_emp_add_form.html(data['form_html']);
                    } else {
                        location.reload();
                    }
                },
                error: function () {
                    employee_emp_add_form.find('.error-message').show()
                }
            });
        });
        employee_emp_delete_btn.click(function () {
            $.ajax({
                url: $(this).data('action'),
                type: $(this).data('method'),
                success: function (data) {
                    location.reload();
                },
                error: function (error) {
                    console.log(error)
                }
            });
        });
    });

</script>

src/administration/admins/templates/admins/include/user_details_tabs_docs.html
{% load static %}
{% load crispy_forms_tags %}

<div class="tab-pane" id="tabs-docs" role="tabpanel">
    {# EMPLOYMENT #}
    <div class="mb-4">
        <div class="text-right mb-2">
            <button class="btn btn-primary" id="employee_document_add_btn">
                + Add Document
            </button>
        </div>

        {% if employee_docs %}
            <div class="row">
                {% for oobject in employee_docs %}
                    <div class="col-sm-3">
                        <div class="card">
                            <div class="ribbon bg-red">
                                <i class="fa fa-trash" id="employee_document_delete_btn"
                                   data-action="{% url 'admins:admins-json:employee_document_delete' oobject.pk %}"
                                   data-param=""
                                   data-method="GET">
                                </i>
                            </div>
                            <div class="card-body text-center">
                                <h1>
                                    <a class="text-primary" href="{{ oobject.file.url }}">
                                        <i class="fa fa-download"></i>
                                    </a>
                                </h1>
                                <h3 class="card-title mb-0">{{ oobject.name }}</h3>
                                <p class="text-muted">uploaded by: {{ oobject.uploaded_by }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div>
                <p class="mb-0 text-danger"><b>Information not available</b></p>
            </div>
        {% endif %}

    </div>
</div>

<div class="modal" tabindex="-1" id="employee_document_add_model">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title">Add Document</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <form method="post" id="employee_document_add_form_data" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% crispy employee_docs_form %}
                </form>
            </div>

            <div class="modal-footer text-left">
                <button type="button" id="employee_document_submit_btn"
                        data-action="{% url 'admins:admins-json:employee_document_add' employee.pk %}" data-param=""
                        data-method="POST"
                        class="btn btn-success me-auto">
                    <i class="fa fa-check"></i>&nbsp;Submit
                </button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        let employee_document_add_btn = $('body #employee_document_add_btn')
        let employee_document_delete_btn = $('body #employee_document_delete_btn')
        let employee_document_submit_btn = $('body #employee_document_submit_btn')
        let employee_document_add_model = $('body #employee_document_add_model')
        let employee_document_add_form = employee_document_add_model.find('form')
        employee_document_add_btn.click(function () {
            employee_document_add_model.modal('show')
        });
        employee_document_submit_btn.click(function () {
            console.log(employee_document_add_form)
            $.ajax({
                url: $(this).data('action'),
                type: $(this).data('method'),
                data: new FormData(document.getElementById('employee_document_add_form_data')),
                cache: false,
                contentType: false,
                processData: false,
                success: function (data) {
                    if (!(data['success'])) {
                        employee_document_add_form.html(data['form_html']);
                    } else {
                        location.reload();
                    }
                },
                error: function () {
                    employee_document_add_form.find('.error-message').show()
                }
            });
        });
        employee_document_delete_btn.click(function () {
            $.ajax({
                url: $(this).data('action'),
                type: $(this).data('method'),
                success: function (data) {
                    location.reload();
                },
                error: function (error) {
                    console.log(error)
                }
            });
        });
    });
</script>