core/urls.py
import notifications
from django.contrib import admin
from django.shortcuts import render, redirect
from django.views.static import serve
from django.urls import path, include, re_path

from .settings import MEDIA_ROOT, STATIC_ROOT, ENVIRONMENT

""" __ ERROR HANDLERS AND VIEWS __ """


def handler404(request, *args, **kwargs):
    return render(request, "404.html")


def handler500(request, *args, **kwargs):
    return render(request, "500.html")


def home(request, *args, **kwargs):
    return redirect('accounts:login')


handler404 = handler404
handler500 = handler500

""" __ URLS __ """

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', home, name='home'),
    path('accounts/', include('src.accounts.urls', namespace='accounts')),
    path('a/', include('src.administration.admins.urls', namespace='admins')),
    path('c/', include('src.administration.employees.urls', namespace='employees')),
    path('scheduler/', include('src.services.schedular.urls', namespace='scheduler')),
]

urlpatterns += [
    path('accounts/', include('allauth.urls')),
    path('inbox/notifications/', include('notifications.urls', namespace='notifications')),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
]

""" __ DEBUG URLS __ """

if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

src/administration/admins/urls.py
from django.urls import path, include
from .views import (
    DashboardView, TimeClockView, CheckCallsView,
    PositionListView, PositionDeleteView, PositionCreateView, PositionUpdateView,
    UserPasswordResetView, UserListView, UserStaffCreateView, UserEmployeeCreateView, UserUpdateView, UserDeleteView,
    ClientListView, ClientDetailView, ClientUpdateView, ClientDeleteView, ClientCreateView,
    SiteListView, SiteDetailView, SiteUpdateView, SiteDeleteView, SiteCreateView,
    ReportTypeListView, ReportTypeUpdateView, ReportTypeDeleteView, ReportTypeCreateView,
    ShiftDayUpdateView, ShiftDayDeleteView,
    ShiftCreateView, ShiftUpdateView, ShiftDeleteView, UserDetailView,
    ShiftListView, ShiftDetailView, ShiftCustomCreateView,
    CountryListView, CountryCreateView, CountryUpdateView, CountryDeleteView, SubContractorListView,
    SubContractorCreateView, SubContractorUpdateView, SubContractorDeleteView, SubContractorDetailView,
    DepartmentListView, DepartmentCreateView, DepartmentUpdateView, DepartmentDeleteView,

    AbsenseTypeListView, AbsenseTypeCreateView, AbsenseTypeDeleteView, AbsenseTypeUpdateView, AbsenseScheduleView,
    UserEmployeeInviteCreateView
)

app_name = 'admins'
urlpatterns = [
    path('', DashboardView.as_view(), name="dashboard"),
    path('time-clock/', TimeClockView.as_view(), name="time-clock"),
    path('absenses/', AbsenseScheduleView.as_view(), name="absense-schedule"),
    path('check-calls/', CheckCallsView.as_view(), name="check-calls"),
]

urlpatterns += [
    path('position/', PositionListView.as_view(), name='position-list'),
    path('position/add/', PositionCreateView.as_view(), name='position-add'),
    path('position/<int:pk>/change/', PositionUpdateView.as_view(), name='position-update'),
    path('position/<int:pk>/delete/', PositionDeleteView.as_view(), name='position-delete'),
]

urlpatterns += [
    path('country/', CountryListView.as_view(), name='country-list'),
    path('country/add/', CountryCreateView.as_view(), name='country-add'),
    path('country/<int:pk>/change/', CountryUpdateView.as_view(), name='country-update'),
    path('country/<int:pk>/delete/', CountryDeleteView.as_view(), name='country-delete'),
]

urlpatterns += [
    path('department/', DepartmentListView.as_view(), name='department-list'),
    path('department/add/', DepartmentCreateView.as_view(), name='department-add'),
    path('department/<int:pk>/change/', DepartmentUpdateView.as_view(), name='department-update'),
    path('department/<int:pk>/delete/', DepartmentDeleteView.as_view(), name='department-delete'),
]

urlpatterns += [
    path('shift/', ShiftListView.as_view(), name='shift-list'),
    path('shift/add/', ShiftCreateView.as_view(), name='shift-add'),
    path('shift/<int:pk>/', ShiftDetailView.as_view(), name='shift-detail'),
    path('shift/<int:pk>/change/', ShiftUpdateView.as_view(), name='shift-update'),
    path('shift/<int:pk>/delete/', ShiftDeleteView.as_view(), name='shift-delete'),
]

urlpatterns += [
    path('shift-day/<int:pk>/change/', ShiftDayUpdateView.as_view(), name='shift-day-update'),
    path('shift-day/<int:pk>/delete/', ShiftDayDeleteView.as_view(), name='shift-day-delete'),
]

urlpatterns += [
    path('client/', ClientListView.as_view(), name='client-list'),
    path('client/add/', ClientCreateView.as_view(), name='client-add'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client-detail'),
    path('client/<int:pk>/change/', ClientUpdateView.as_view(), name='client-update'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client-delete'),
]

urlpatterns += [
    path('site/', SiteListView.as_view(), name='site-list'),
    path('site/add/', SiteCreateView.as_view(), name='site-add'),
    path('site/<int:pk>/', SiteDetailView.as_view(), name='site-detail'),
    path('site/<int:pk>/change/', SiteUpdateView.as_view(), name='site-update'),
    path('site/<int:pk>/delete/', SiteDeleteView.as_view(), name='site-delete'),
]

urlpatterns += [
    path('report-type/', ReportTypeListView.as_view(), name='report-type-list'),
    path('report-type/add/', ReportTypeCreateView.as_view(), name='report-type-add'),
    path('report-type/<int:pk>/change/', ReportTypeUpdateView.as_view(), name='report-type-update'),
    path('report-type/<int:pk>/delete/', ReportTypeDeleteView.as_view(), name='report-type-delete'),
]

urlpatterns += [
    path('absense-type/', AbsenseTypeListView.as_view(), name='absense-type-list'),
    path('absense-type/add/', AbsenseTypeCreateView.as_view(), name='absense-type-add'),
    path('absense-type/<int:pk>/change/', AbsenseTypeUpdateView.as_view(), name='absense-type-update'),
    path('absense-type/<int:pk>/delete/', AbsenseTypeDeleteView.as_view(), name='absense-type-delete'),
]

urlpatterns += [
    path('sub-contractor/', SubContractorListView.as_view(), name='sub-contractor-list'),
    path('sub-contractor/add/', SubContractorCreateView.as_view(), name='sub-contractor-add'),
    path('sub-contractor/<int:pk>/', SubContractorDetailView.as_view(), name='sub-contractor-detail'),
    path('sub-contractor/<int:pk>/change/', SubContractorUpdateView.as_view(), name='sub-contractor-update'),
    path('sub-contractor/<int:pk>/delete/', SubContractorDeleteView.as_view(), name='sub-contractor-delete'),
]

urlpatterns += [
    path('user/', UserListView.as_view(), name='user-list'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/<int:pk>/change/', UserUpdateView.as_view(), name='user-update'),
    path('user/<int:pk>/delete/', UserDeleteView.as_view(), name='user-delete'),
    path('user/staff/add/', UserStaffCreateView.as_view(), name='user-staff-add'),
    path('user/employee/add/', UserEmployeeCreateView.as_view(), name='user-employee-add'),
    path('user/employee/invite/add/', UserEmployeeInviteCreateView.as_view(), name='user-employee-invite-add'),
    path('user/<int:pk>/reset/password/', UserPasswordResetView.as_view(), name='user-password-reset'),
]

urlpatterns += [
    path('api/', include('src.administration.admins.admins-api.urls', namespace='admins-api')),
    path('json/', include('src.administration.admins.admins-json.urls', namespace='admins-json'))
]

src/administration/employees/urls.py
from django.urls import path
from .views import (
    DashboardView, ShiftListView, ShiftDetailView
)

app_name = 'employees'
urlpatterns = [

    path('', DashboardView.as_view(), name="dashboard"),
    path('my/shift/', ShiftListView.as_view(), name="shift-list"),
    path('my/shift/<int:pk>/', ShiftDetailView.as_view(), name="shift-detail"),

]

src/administration/employees/views.py
import datetime

from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, ListView, DetailView, UpdateView

from src.accounts.decorators import employee_protected
from src.administration.admins.models import Shift


@method_decorator(employee_protected, name='dispatch')
class DashboardView(TemplateView):
    template_name = 'employees/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['shifts'] = Shift.objects.filter(employee__user=self.request.user)
        return context


@method_decorator(employee_protected, name='dispatch')
class ShiftListView(ListView):
    template_name = 'employees/shift_list.html'

    def get_queryset(self):
        return Shift.objects.filter(employee__user=self.request.user)


@method_decorator(employee_protected, name='dispatch')
class ShiftDetailView(DetailView):
    model = Shift
    template_name = 'employees/shift_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ShiftDetailView, self).get_context_data(**kwargs)
        context['current_date'] = datetime.date.today()
        return context

src/administration/admins/templates/admins/absensetype_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_subtitle %}Absense Type Delete{% endblock %}
{% block base_subhead_heading %}Absense Type &rAarr; Delete {% endblock %}
{% block base_subhead_paragraph %}Delete Absense Type permanently{% endblock %}
{% block base_subhead_button %}
    <a href="{% url 'admins:absense-type-list' %}">&larr; Absense Types</a>
{% endblock %}

{% block base_content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">

                    <form method="post">{% csrf_token %}
                        <p class="mb-2">Are you sure you want to delete <b class="text-danger">"{{ object }}"</b>?</p>
                        <input type="submit" class="btn btn-danger" value="Confirm">
                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/administration/admins/templates/admins/absensetype_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_subtitle %} Absense Types{% endblock %}
{% block base_subhead_heading %} Absense Types &rAarr; List{% endblock %}
{% block base_subhead_paragraph %}List of all available Absense types{% endblock %}

{% block base_subhead_button %}
    <a class="btn btn-primary" href="{% url 'admins:absense-type-add' %}">
        Add Absense Type
    </a>
{% endblock %}

{% block base_content %}

    <div class="row">
        <div class="col-12">
            <div class="card">
                {% if object_list %}

                    <div class="table-responsive">
                    <table class="table table-hover">
                        <thead class="thead-light">
                        <tr>
                            <th>Name</th>
                            <th>Paid</th>
                            <th>-</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for object in object_list %}
                            <tr>
                                <td>{{ object.name }}</td>
                                <td>
                                    {% if object.is_paid %}
                                        <b class="text-success"><i class="fa fa-check"></i></b>
                                    {% else %}
                                        <b class="text-danger"><i class="fa fa-times"></i></b>
                                    {% endif %}
                                </td>
                                <th>
                                    <a href="{% url 'admins:absense-type-update' object.pk %}">
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             class="icon icon-tabler icon-tabler-edit-circle" width="24" height="24"
                                             viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                             stroke-linecap="round" stroke-linejoin="round">
                                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                            <path d="M12 15l8.385 -8.415a2.1 2.1 0 0 0 -2.97 -2.97l-8.415 8.385v3h3z"></path>
                                            <path d="M16 5l3 3"></path>
                                            <path d="M9 7.07a7.002 7.002 0 0 0 1 13.93a7.002 7.002 0 0 0 6.929 -5.999"></path>
                                        </svg>
                                    </a> &nbsp;
                                    <a href="{% url 'admins:absense-type-delete' object.pk %}" class="text-danger">
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             class="icon icon-tabler icon-tabler-trash" width="24" height="24"
                                             viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                             stroke-linecap="round" stroke-linejoin="round">
                                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                            <line x1="4" y1="7" x2="20" y2="7"></line>
                                            <line x1="10" y1="11" x2="10" y2="17"></line>
                                            <line x1="14" y1="11" x2="14" y2="17"></line>
                                            <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12"></path>
                                            <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3"></path>
                                        </svg>
                                    </a>
                                </th>
                            </tr>
                        {% endfor %}


                        </tbody>
                    </table>

                {% else %}
                    <div class="card-body">
                        <p class="text-danger mb-0"><b>No objects available</b></p>
                    </div>
                {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/administration/admins/templates/admins/client_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_subtitle %}Client Delete{% endblock %}
{% block base_subhead_heading %}Client &rAarr; Delete {% endblock %}
{% block base_subhead_paragraph %}Delete Client permanently{% endblock %}
{% block base_subhead_button %}
    <a href="{% url 'admins:client-list' %}">&larr; Clients</a>
{% endblock %}

{% block base_content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">

                    <form method="post">{% csrf_token %}
                        <p class="mb-2">Are you sure you want to delete <b class="text-danger">"{{ object.name }}"</b>?</p>
                        <input type="submit" class="btn btn-danger" value="Confirm">
                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/administration/admins/templates/admins/client_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_subtitle %}Client Details{% endblock %}
{% block base_subhead_heading %}Client &rAarr; Details {% endblock %}
{% block base_subhead_paragraph %}Client detailed view{% endblock %}
{% block base_subhead_button %}
    <b>
        <a href="{% url 'admins:client-list' %}">
            &larr; Clients
        </a>
    </b>
    <b>
        <a class="" href="{% url 'admins:client-update' object.pk %}">
            <i class="fa fa-edit"></i> Edit
        </a>
    </b>
{% endblock %}


{% block base_content %}

    <div class="row mb-4">
        <div class="col-sm-8">

            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs" data-bs-toggle="tabs" role="tablist">
                        <li class="nav-item" role="presentation">
                            <a href="#tabs-home-13" class="nav-link active" data-bs-toggle="tab" aria-selected="true"
                               role="tab"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon me-2" width="24" height="24"
                                     viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                     stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <path d="M3 12h4l3 8l4 -16l3 8h4"></path>
                                </svg>
                                Sites</a>
                        </li>
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content">
                        <div class="tab-pane active show" id="tabs-home-13" role="tabpanel">
                            <div>
                                {% if not object.get_sites %}
                                    <p class="mb-0 text-danger">
                                        Not sites available.
                                    </p>
                                {% else %}
                                    <div class="table-responsive">
                                        <table class="table table-hover">
                                            <thead class="thead-light">
                                            <tr>
                                                <th>ID</th>
                                                <th>Name</th>
                                                <th>Location</th>
                                                <th>Display ID</th>
                                                <th>-</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for site in object.get_sites %}
                                                <tr>
                                                    <td>{{ site.site_id }}</td>
                                                    <td>{{ site.name }}</td>
                                                    <td>{{ site.address }}</td>
                                                    <td>{{ site.pk }}</td>
                                                    <td>
                                                        <b>
                                                            <a href="{% url 'admins:site-detail' site.pk %}">
                                                                <svg xmlns="http://www.w3.org/2000/svg"
                                                                     class="icon icon-tabler icon-tabler-eye" width="24"
                                                                     height="24"
                                                                     viewBox="0 0 24 24" stroke-width="2"
                                                                     stroke="currentColor"
                                                                     fill="none"
                                                                     stroke-linecap="round" stroke-linejoin="round">
                                                                    <path stroke="none" d="M0 0h24v24H0z"
                                                                          fill="none"></path>
                                                                    <circle cx="12" cy="12" r="2"></circle>
                                                                    <path d="M22 12c-2.667 4.667 -6 7 -10 7s-7.333 -2.333 -10 -7c2.667 -4.667 6 -7 10 -7s7.333 2.333 10 7"></path>
                                                                </svg>
                                                            </a>
                                                        </b>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-sm-4">

            <div class="card mb-2">
                <div class="card-body">
                    <div class="card-title">
                        More information
                    </div>
                    <div class="mb-2">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon text-muted" width="24"
                             height="24"
                             viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                             stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M3 19a9 9 0 0 1 9 0a9 9 0 0 1 9 0"></path>
                            <path d="M3 6a9 9 0 0 1 9 0a9 9 0 0 1 9 0"></path>
                            <line x1="3" y1="6" x2="3" y2="19"></line>
                            <line x1="12" y1="6" x2="12" y2="19"></line>
                            <line x1="21" y1="6" x2="21" y2="19"></line>
                        </svg>
                        Name: <strong>{{ object.name }}</strong>
                    </div>
                    <div class="mb-2">
                        <svg xmlns="http://www.w3.org/2000/svg"
                             class="icon icon-tabler icon-tabler-phone-calling text-muted"
                             width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"
                             fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M5 4h4l2 5l-2.5 1.5a11 11 0 0 0 5 5l1.5 -2.5l5 2v4a2 2 0 0 1 -2 2a16 16 0 0 1 -15 -15a2 2 0 0 1 2 -2"></path>
                            <line x1="15" y1="7" x2="15" y2="7.01"></line>
                            <line x1="18" y1="7" x2="18" y2="7.01"></line>
                            <line x1="21" y1="7" x2="21" y2="7.01"></line>
                        </svg>
                        Phone: <strong>
                        {% if not object.phone %}
                            <a href="#" class="">-</a>
                        {% else %}
                            <a href="tel:{{ object.phone }}">{{ object.phone }}</a>
                        {% endif %}
                    </strong>
                    </div>
                    <div class="mb-2">
                        <svg xmlns="http://www.w3.org/2000/svg"
                             class="icon icon-tabler icon-tabler-mail-fast text-muted"
                             width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"
                             fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M3 7h3"></path>
                            <path d="M3 11h2"></path>
                            <path d="M9.02 8.801l-.6 6a2 2 0 0 0 1.99 2.199h7.98a2 2 0 0 0 1.99 -1.801l.6 -6a2 2 0 0 0 -1.99 -2.199h-7.98a2 2 0 0 0 -1.99 1.801z"></path>
                            <path d="M9.8 7.5l2.982 3.28a3 3 0 0 0 4.238 .202l3.28 -2.982"></path>
                        </svg>
                        Email: <strong>
                        {% if not object.email %}
                            <a href="#" class="">-</a>
                        {% else %}
                            <a href="mailto:{{ object.email }}">{{ object.email }}</a>
                        {% endif %}
                    </strong>
                    </div>
                    <div class="mb-2">
                        <svg xmlns="http://www.w3.org/2000/svg"
                             class="icon icon-tabler icon-tabler-rubber-stamp text-muted"
                             width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"
                             fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M21 17.85h-18c0 -4.05 1.421 -4.05 3.79 -4.05c5.21 0 1.21 -4.59 1.21 -6.8a4 4 0 1 1 8 0c0 2.21 -4 6.8 1.21 6.8c2.369 0 3.79 0 3.79 4.05z"></path>
                            <path d="M5 21h14"></path>
                        </svg>
                        Registration: <strong>{{ object.registration_number }}</strong>
                    </div>
                    <div class="mb-2">
                        <svg xmlns="http://www.w3.org/2000/svg"
                             class="icon icon-tabler icon-tabler-message-share text-muted"
                             width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"
                             fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M20 11v3a3 3 0 0 1 -3 3h-9l-4 4v-13a3 3 0 0 1 3 -3h7"></path>
                            <path d="M17 4h4v4"></path>
                            <path d="M16 9l5 -5"></path>
                        </svg>
                        VAT: <strong>{{ object.vat_number }}</strong>
                    </div>
                    <div class="mb-2">
                        <svg xmlns="http://www.w3.org/2000/svg"
                             class="icon icon-tabler icon-tabler-world-upload text-muted"
                             width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"
                             fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M21 12a9 9 0 1 0 -9 9"></path>
                            <path d="M3.6 9h16.8"></path>
                            <path d="M3.6 15h8.4"></path>
                            <path d="M11.578 3a17 17 0 0 0 0 18"></path>
                            <path d="M12.5 3c1.719 2.755 2.5 5.876 2.5 9"></path>
                            <path d="M18 21v-7m3 3l-3 -3l-3 3"></path>
                        </svg>
                        Website: <strong>
                        {% if not object.website %}
                            <a href="#" class="text-danger">-</a>
                        {% else %}
                            <a href="{{ object.website }}" target="_blank">{{ object.website }}</a>
                        {% endif %}
                    </strong>
                    </div>
                    <div class="mb-2">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-map-pin text-muted"
                             width="24"
                             height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                             stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <circle cx="12" cy="11" r="3"></circle>
                            <path d="M17.657 16.657l-4.243 4.243a2 2 0 0 1 -2.827 0l-4.244 -4.243a8 8 0 1 1 11.314 0z"></path>
                        </svg>
                        Address: <strong>{{ object.address }} - {{ object.city }} - {{ object.country }}</strong>
                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    <div class="card-title">Actions</div>
                    <p class="mb-3 text-muted">
                        Make sure you want to delete this client permanently, once deleted there is
                        no way to retrieve user again.
                    </p>
                    <a class="btn btn-danger" href="{% url 'admins:client-delete' object.pk %}">
                        Delete
                    </a>
                </div>
            </div>

        </div>
    </div>

{% endblock %}

src/administration/admins/templates/admins/country_form.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block base_subtitle %}Country Form {% endblock %}
{% block base_subhead_heading %}Country &rAarr; Form {% endblock %}
{% block base_subhead_paragraph %}Country create/update form{% endblock %}
{% block base_subhead_button %}
    <a href="{% url 'admins:country-list' %}">&larr; Countries</a>
{% endblock %}


{% block base_content %}

    <div class="row justify-content-center">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">

                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary">
                            <i class="fa fa-check-circle"></i> Submit
                        </button>
                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block base_external_scripts %}
    <script>
    $(document).ready(function (){
        $('input').addClass('my-2');
    })
    </script>
{% endblock %}

src/administration/admins/templates/admins/position_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block base_title %}admins | {{ object }}{% endblock %}
{% block base_subhead_heading %} {{ object }}{% endblock %}
{% block base_subhead_paragraph %}Detail down description of {{ object }}.{% endblock %}
{% block base_subhead_button %}
    <a class="btn btn-primary" href="{% url 'admins:position-list' %}"><i class="fa fa-arrow-left"></i> Positions</a>
{% endblock %}


{% block base_content %}

    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body text-center">
                    <p class="display-1"><i class="fa fa-hammer"></i></p>
                    <p class="mb-0 card-title text-danger">
                        <b>EXIMITAS <small>Says.</small></b>
                    </p>

                    <p class="lead">Sorry for inconvenience the page is under-development.</p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}